### ISSUE TITLE
Error unique "key" prop

### ISSUE THREAD

**Issue by albertcito** [Kombustor/antd-password-input-strength#3] opened 2019-02-03 04:23 UTC
- This is the error when I used the PasswordInput 
- Also maybe you may use the new version input for password [Input.Password](https://codesandbox.io/s/m7qov3qrox)
- It's possible to add a validator as a minimum strength?

> index.js:2178 Warning: Each child in an array or iterator should have a unique "key" prop.
> 
> Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
>     in div
>     in Unknown (created by PasswordInput)
>     in div (created by PasswordInput)
>     in PasswordInput (at Password.js:18)
>     in span (created by Context.Consumer)

**Comment by Kombustor** [comment] 2019-02-03 04:55
Could you please create a reproduction of the error on codesandbox? I can't reproduce it on myself.
The error normally occurs when you create a list of components without adding a key="uniquekey..." property to every list-element.

I'll release a new version with the new Input.Password component, and the validator is on my todo-list!

**Comment by Kombustor** [comment] 2019-02-03 06:10
Fixed in #4

**Closed** 2019-02-03 06:10 UTC
Labels: bug, enhancement
